const SEVERITIES = new Set(["critical", "warning", "suggestion", "nit", "praise"]);
const VERDICTS = new Set(["approve", "comment", "request_changes"]);

/**
 * @param {string} text
 * @returns {{ summary: string, verdict: string, findings: object[], raw: string, parsed: boolean }}
 */
export function parseReviewResponse(text) {
  const raw = String(text ?? "").trim();
  const jsonText = extractJson(raw);

  if (!jsonText) {
    return fallback(raw);
  }

  try {
    const data = JSON.parse(jsonText);
    const findings = Array.isArray(data.findings)
      ? data.findings.map(normalizeFinding).filter(Boolean)
      : [];
    const verdict = VERDICTS.has(data.verdict) ? data.verdict : inferVerdict(findings);
    return {
      summary: String(data.summary || "").trim() || "Review completed.",
      verdict,
      findings,
      raw,
      parsed: true,
    };
  } catch {
    return fallback(raw);
  }
}

function extractJson(text) {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = fenced ? fenced[1].trim() : text;
  const start = candidate.indexOf("{");
  const end = candidate.lastIndexOf("}");
  if (start === -1 || end <= start) return null;
  return candidate.slice(start, end + 1);
}

function normalizeFinding(item) {
  if (!item || typeof item !== "object") return null;
  const title = String(item.title || item.headline || "").trim();
  const body = String(item.body || item.comment || item.message || "").trim();
  if (!title && !body) return null;

  let severity = String(item.severity || "suggestion").toLowerCase();
  if (severity === "error" || severity === "blocker" || severity === "high") severity = "critical";
  if (severity === "medium") severity = "warning";
  if (severity === "low" || severity === "info") severity = "suggestion";
  if (!SEVERITIES.has(severity)) severity = "suggestion";

  const lineRaw = item.line ?? item.start_line;
  const line = Number.parseInt(lineRaw, 10);

  return {
    severity,
    file: item.file ? String(item.file) : null,
    line: Number.isInteger(line) && line > 0 ? line : null,
    title: title || severity,
    body,
  };
}

function inferVerdict(findings) {
  if (findings.some((f) => f.severity === "critical")) return "request_changes";
  if (findings.some((f) => f.severity === "warning")) return "comment";
  return "approve";
}

function fallback(raw) {
  return {
    summary: raw.slice(0, 400) || "The model did not return structured findings.",
    verdict: "comment",
    findings: raw
      ? [{ severity: "suggestion", file: null, line: null, title: "Unstructured review", body: raw }]
      : [],
    raw,
    parsed: false,
  };
}

/**
 * @param {{ summary: string, verdict: string, findings: object[], pr?: object }} review
 */
export function reviewToMarkdown(review) {
  const verdictLabel = {
    approve: "Approve",
    comment: "Comment",
    request_changes: "Request changes",
  }[review.verdict] || review.verdict;

  const lines = [
    "## AI pull request review",
    "",
    `**Verdict:** ${verdictLabel}`,
    "",
    review.summary,
    "",
  ];

  if (!review.findings.length) {
    lines.push("_No findings._");
    return lines.join("\n").trim() + "\n";
  }

  const groups = groupBySeverity(review.findings);
  for (const [severity, items] of groups) {
    lines.push(`### ${capitalize(severity)}`);
    lines.push("");
    for (const item of items) {
      const loc = [item.file, item.line].filter(Boolean).join(":");
      lines.push(`- **${item.title}**${loc ? ` (\`${loc}\`)` : ""}`);
      if (item.body) {
        for (const paragraph of item.body.split(/\n+/)) {
          lines.push(`  ${paragraph}`);
        }
      }
    }
    lines.push("");
  }

  lines.push("_Generated by [PR Review](https://github.com). Treat it as assistance, not a substitute for human review._");
  return lines.join("\n").trim() + "\n";
}

function groupBySeverity(findings) {
  const order = ["critical", "warning", "suggestion", "nit", "praise"];
  return order
    .map((severity) => [severity, findings.filter((f) => f.severity === severity)])
    .filter(([, items]) => items.length);
}

function capitalize(value) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}